- packages/service-frontend/app/page.tsx
- packages/service-frontend/package.json
- packages/ui/.eslintrc.cjs
- packages/ui/.gitignore
- packages/ui/.storybook/main.ts
- packages/ui/.storybook/preview.ts
- packages/ui/package.json
- packages/ui/postcss.config.js
- packages/ui/src/components/Button.tsx
- packages/ui/src/components/index.ts
- packages/ui/src/index.ts
- packages/ui/src/stories/Button.stories.tsx
- packages/ui/src/stories/Introduction.mdx
- packages/ui/src/tailwind.css
- packages/ui/tailwind.config.js
- packages/ui/tsconfig.json
- packages/ui/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> Feat: add ppoba-ui workspace (storybook setting)

- packages/service-frontend/.eslintrc.json
- packages/service-frontend/jest.config.js
- packages/service-frontend/jest.setup.js
- packages/service-frontend/package.json
- pnpm-lock.yaml
- 프론트엔드 코드 테스트를 위해 Jest 등 필요한 패키지를 설치
- 예시 테스트 코드 작성
> Feat: configure Jest for unit testing

- packages/service-frontend/app/deck/[id]/layout.tsx
- packages/service-frontend/app/deck/[id]/page.tsx
- packages/service-frontend/app/deck/[id]/play/layout.tsx
- packages/service-frontend/app/deck/[id]/play/page.tsx
- packages/service-frontend/package.json
- packages/tailwind-config/tailwind.config.js
- pnpm-lock.yaml
- Add Typography to Tailwind Config
- Add Color Theme to Tailwind Config
- Add default folder structure for deck-play subtree
- Add Framer Motion Package
> Implement Design-System Typography and Color Theme

- packages/service-frontend/app/LoginHeader.tsx
- packages/service-frontend/app/deck/[id]/layout.tsx
- packages/service-frontend/app/deck/[id]/page.tsx
- packages/service-frontend/app/deck/[id]/play/layout.tsx
- packages/service-frontend/app/login/layout.tsx
- packages/service-frontend/app/page.tsx
- packages/service-frontend/components/Header.tsx
- packages/service-frontend/components/index.ts
- packages/tailwind-config/tailwind.config.js
- packages/ui/src/components/Icon.tsx
#14 
- header에 색상은 className으로 주입받으면 될 것 같아요!
> feat: add header component(gnb)

- packages/service-backend/src/modules/card/CardRepository.ts
- packages/service-backend/src/modules/card/CardService.ts
> feat: add card update api

- packages/service-backend/package.json
- packages/service-backend/src/modules/card/CardController.ts
- packages/service-backend/src/modules/card/CardRepository.ts
- packages/service-backend/src/modules/card/CardService.ts
> feat: add soft-delete-plugin-mongoose to package.json & remove annotation

- packages/service-backend/src/core/database/Card.ts
- packages/service-backend/src/modules/card/CardController.ts
- packages/service-backend/src/modules/card/CardRepository.ts
- packages/service-backend/src/modules/card/CardService.ts
close: #49 
> 단일 카드 업로드 -> bulk 카드 업로드
@pjw5521 
> refactor: change create card bulk api

- packages/service-backend/src/core/database/Deck.ts
- packages/service-backend/src/modules/deck/DeckConstant.ts
- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/DeckRepository.ts
- packages/service-backend/src/modules/deck/DeckService.ts
- packages/service-backend/src/modules/deck/dto/CreateDeckDto.ts
> refactor: Apply class-validate to deck category & change type to enum deck model category schema property

- packages/service-backend/src/modules/card/CardController.ts
- packages/service-backend/src/modules/card/CardRepository.ts
- packages/service-backend/src/modules/card/CardService.ts
- packages/service-backend/src/modules/card/dto/createCardDto.ts
close: #53 
> card 생성 api request body 포맷 수정
- 전달 사항 1
- 전달 사항 2
> refactor: create card api modify request body

- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/dto/CreateDeckDto.ts
- packages/service-backend/src/modules/deck/dto/UpdateDeckDto.ts
close: #61 
list of swagger additions
N/A
> feat: add deck api swagger ( POST, GET ) 

- packages/service-backend/src/bootstrap.ts
close: #68 
- 전달 사항 1
- 전달 사항 2
> feat: node attach sentry

- packages/service-frontend/app/provider.client.tsx
- packages/service-frontend/package.json
- packages/service-frontend/store/index.ts
- packages/service-frontend/store/test.ts
- pnpm-lock.yaml
close: #66 
- pnpm-lock.yaml 파일의 indent가 바뀌었는데 왜..그런진 모르겠네요 아시는 분?ㅠ
> feat: setup recoil

- packages/service-backend/src/bootstrap.ts
> fix: erase unused sentry options

- packages/api/src/index.ts
- packages/service-backend/src/modules/card/CardController.ts
- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/DeckRepository.ts
- packages/service-backend/src/modules/deck/DeckService.ts
> feat: Add deck, card client api & set return type of deck, card api

- packages/service-frontend/app/complete/page.tsx
- packages/service-frontend/app/components/marketplace/game/GameCardListTitle.tsx
- packages/service-frontend/app/confirm-detail/page.tsx
- packages/service-frontend/app/create-deck/page.tsx
- packages/service-frontend/app/create-title/page.tsx
- packages/service-frontend/middleware.ts
close: #71
- 전달 사항 1
- 전달 사항 2
> feat: add router link to pages

- packages/service-frontend/app/complete/page.tsx
- packages/service-frontend/app/components/marketplace/game/GameCardListTitle.tsx
- packages/service-frontend/app/confirm-detail/page.tsx
- packages/service-frontend/app/create-deck/page.tsx
- packages/service-frontend/app/create-title/page.tsx
- packages/service-frontend/app/deck/[id]/play/Card.tsx
- packages/service-frontend/app/deck/[id]/play/generateCard.ts
- packages/service-frontend/app/deck/[id]/play/page.tsx
- packages/service-frontend/app/deck/[id]/tarot/TaroCardList.tsx
- packages/service-frontend/app/deck/[id]/tarot/layout.tsx
- packages/service-frontend/app/deck/[id]/tarot/page.tsx
- packages/service-frontend/middleware.ts
- packages/tailwind-config/tailwind.config.js
> Rebase branch

- packages/service-backend/src/modules/auth/AuthKakaoService.ts
> feat: auth login catch sentry

- packages/api/src/index.ts
- packages/types/src/database/Card.ts
- packages/types/src/database/Deck.ts
- packages/types/src/dto/createCardDto.ts
- packages/types/src/dto/createDeckDto.ts
> feat: client api apply

- packages/api/src/index.ts
- packages/types/src/database/index.ts
- packages/types/src/dto/index.ts
- packages/types/src/index.ts
> refactor: export index type

- packages/api/src/index.ts
- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/DeckRepository.ts
- packages/service-backend/src/modules/deck/DeckService.ts
> feat: add getAllDeck api

- packages/api/src/index.ts
- packages/service-backend/src/modules/auth/AuthKakaoService.ts
- packages/service-backend/src/modules/auth/AuthService.ts
- packages/service-backend/src/modules/user/UserRepository.ts
> feat: apply auth api sentry

- packages/api/src/index.ts
> fix: delete-deck client-api response promise

- packages/api/src/index.ts
> refactor: Change session to public for testing

- packages/service-backend/src/modules/card/CardRepository.ts
- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/DeckRepository.ts
- packages/service-backend/src/modules/deck/DeckService.ts
- packages/types/src/database/Card.ts
> refactor: deck api response model

- packages/service-frontend/app/login/hooks.ts
close: #103 
- (to. backend) 실행이 잘 될지 확인 한 번 부탁합니다..!
> fix: prevent login logic execution when code is empty

- packages/api/src/index.ts
- packages/service-frontend/app/components/marketplace/game/GameCardList.tsx
- packages/service-frontend/app/create-template/page.tsx
- packages/service-frontend/app/page.tsx
> fix: fix build error

- packages/api/src/index.ts
- packages/service-frontend/app/deck/[id]/normal/components/NormalCard.tsx
- packages/service-frontend/app/deck/[id]/normal/page.tsx
- packages/service-frontend/app/deck/[id]/page.tsx
- packages/service-frontend/app/deck/[id]/play/generateCard.ts
- packages/service-frontend/app/deck/[id]/tarot/page.tsx
> feat: implement api call on detail page

- packages/service-frontend/app/create-deck/page.tsx
- packages/service-frontend/app/create-title/page.tsx
- packages/service-frontend/store/deck.ts
> feat: add util function in create-deck

- packages/service-frontend/app/deck/[id]/page.tsx
- packages/service-frontend/app/my-deck/page.tsx
- my-deck 쪽이 API 연결이 안 되어 있어서 생겼던 이슈 입니다~
> feat: connect my-deck page with api

- packages/api/src/index.ts
- packages/service-backend/src/core/database/User.ts
- packages/service-backend/src/core/database/index.ts
- packages/service-backend/src/core/decorators/AuthUser.ts
- packages/service-backend/src/core/decorators/Public.ts
- packages/service-backend/src/core/decorators/index.ts
- packages/service-backend/src/core/metrics/MetricController.ts
- packages/service-backend/src/modules/auth/AuthController.ts
- packages/service-backend/src/modules/auth/AuthGuard.ts
- packages/service-backend/src/modules/auth/AuthModule.ts
- packages/service-backend/src/modules/auth/AuthService.ts
- packages/service-backend/src/modules/auth/JwtService.ts
- packages/service-backend/src/modules/card/CardController.ts
- packages/service-backend/src/modules/deck/DeckController.ts
- packages/service-backend/src/modules/deck/DeckService.ts
- packages/service-backend/src/modules/deck/dto/CreateDeckDto.ts
- packages/service-backend/src/modules/user/UserRepository.ts
- packages/types/src/User.ts
- packages/types/src/dto/createDeckDto.ts
- packages/types/src/index.ts
> feat(backend, api client): apply auth route and add getMyDeck api

- packages/service-backend/src/modules/card/CardModule.ts
- packages/service-backend/src/modules/card/CardService.ts
- packages/service-backend/src/modules/deck/DeckModule.ts
- packages/service-backend/src/modules/deck/DeckRepository.ts
> refactor: update deck totalCardCount column at create card api

- packages/service-frontend/app/deck/[id]/normal/page.tsx
- packages/service-frontend/app/globals.css
> feat: fix-font and resolve chores

- packages/service-frontend/app/complete/page.tsx
- packages/service-frontend/app/components/common/Header.tsx
- packages/service-frontend/app/confirm-detail/page.tsx
- packages/service-frontend/app/deck/[id]/play/page.tsx
- packages/service-frontend/app/layout.tsx
> fix: apply front QA

- packages/service-frontend/app/deck/[id]/DeckDetail.tsx
- packages/service-frontend/app/loading.tsx
> feat: fix design qa 2
